name: "GO CI"

on:

  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:

  buildDocker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build docker images
        run: docker-compose up -d --build
      - name: Check running containers
        run: docker ps -a


  RunTests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.23.3']

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Build
        run: go build
      - name: Get file list
        run: ls -A
      - name: Run tests
        run: go test -v ./...
#      - name: run code linter
#        uses: golangci/golangci-lint-action@v6
#        with:
#          version: v1.60